var solitaires={
  klondike:{
    name:"Klondike",
    cardinfo:{
      viewmode:"down",  //default direction cards are placed
      cardcount:[13]   //hearts,clubs,diamonds,spades
    },
    generalinfo:{
      redeals:Infinity,
      checks:"none",
      autoplace:true
    },
    board:[[
      {type:"deck",mode:"normal",dealcount:1},
      {type:"deckdump",display:1},
      {type:"invisible"},
      {vardef:{
        criteria:"0|same|asc|any"
      }},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"}
    ],[
      {vardef:{
        criteria:"14|alternate|desc|any"
      }},
      {type:"heap",startsize:1},
      {type:"heap",startsize:2},
      {type:"heap",startsize:3},
      {type:"heap",startsize:4},
      {type:"heap",startsize:5},
      {type:"heap",startsize:6},
      {type:"heap",startsize:7}
    ]]
  },
  klondikebythrees:{
    name:"Klondike by Threes",
    cardinfo:{
      viewmode:"down",  //default direction cards are placed
      cardcount:[13]   //hearts,clubs,diamonds,spades
    },
    generalinfo:{
      redeals:Infinity,
      checks:"none",
      autoplace:true
    },
    board:[[
      {type:"deck",mode:"normal",dealcount:3},
      {type:"deckdump",display:3},
      {type:"invisible"},
      {vardef:{
        criteria:"0|same|asc|any"
      }},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"}
    ],[
      {vardef:{
        criteria:"14|alternate|desc|any"
      }},
      {type:"heap",startsize:1},
      {type:"heap",startsize:2},
      {type:"heap",startsize:3},
      {type:"heap",startsize:4},
      {type:"heap",startsize:5},
      {type:"heap",startsize:6},
      {type:"heap",startsize:7}
    ]]
  },
  spider:{
    name:"Spider",
    cardinfo:{
      viewmode:"down",  //default direction cards are placed
      cardcount:[0,0,0,104]   //hearts,clubs,diamonds,spades
    },
    generalinfo:{
      redeals:0,
      checks:"flush",
      autoplace:true
    },
    board:[[
      {type:"deck",mode:"packets",packetsize:10},
      {type:"invisible"},
      {type:"invisible"},
      {vardef:{
        criteria:"0|same|asc|any|auto"
      }},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"}
    ],[
      {vardef:{
        criteria:"any|same|desc|any"
      }},
      {type:"heap",startsize:6},
      {type:"heap",startsize:6},
      {type:"heap",startsize:6},
      {type:"heap",startsize:6},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5}
    ]]
  },
  spider2s:{
    name:"Spider - Two Suits",
    cardinfo:{
      viewmode:"down",  //default direction cards are placed
      cardcount:[52,0,0,52]   //hearts,clubs,diamonds,spades
    },
    generalinfo:{
      redeals:0,
      checks:"flush",
      maxstack:{same:["suit"]},
      autoplace:true
    },
    board:[[
      {type:"deck",mode:"packets",packetsize:10},
      {type:"invisible"},
      {type:"invisible"},
      {vardef:{
        criteria:"0|same|asc|any|auto"
      }},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"}
    ],[
      {vardef:{
        criteria:"any|alternate|desc|any|null|anysuit|true"
      }},
      {type:"heap",startsize:6},
      {type:"heap",startsize:6},
      {type:"heap",startsize:6},
      {type:"heap",startsize:6},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5}
    ]]
  },
  spider4s:{
    name:"Spider - Four Suits",
    cardinfo:{
      viewmode:"down",  //default direction cards are placed
      cardcount:[26]   //hearts,clubs,diamonds,spades
    },
    generalinfo:{
      redeals:0,
      checks:"flush",
      maxstack:{same:["suit"]},
      autoplace:true
    },
    board:[[
      {type:"deck",mode:"packets",packetsize:10},
      {type:"invisible"},
      {type:"invisible"},
      {vardef:{
        criteria:"0|same|asc|any|auto"
      }},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"}
    ],[
      {vardef:{
        criteria:"any|alternate|desc|any|null|anysuit|true"
      }},
      {type:"heap",startsize:6},
      {type:"heap",startsize:6},
      {type:"heap",startsize:6},
      {type:"heap",startsize:6},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5}
    ]]
  },
  fortythieves:{
    name:"Forty Thieves",
    cardinfo:{
      viewmode:"up",  //default direction cards are placed
      cardcount:[26]   //hearts,clubs,diamonds,spades
    },
    generalinfo:{
      redeals:0,
      checks:"none",
      maxstack:1,
      autoplace:true
    },
    board:[[
      {type:"deck",mode:"normal",dealcount:1},
      {type:"deckdump",display:1},
      {vardef:{
        criteria:"0|same|asc|any"
      }},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"}
    ],[
      {vardef:{
        criteria:"any|same|desc|any"
      }},
      {type:"heap",startsize:4},
      {type:"heap",startsize:4},
      {type:"heap",startsize:4},
      {type:"heap",startsize:4},
      {type:"heap",startsize:4},
      {type:"heap",startsize:4},
      {type:"heap",startsize:4},
      {type:"heap",startsize:4},
      {type:"heap",startsize:4},
      {type:"heap",startsize:4}
    ]]
  },
  freecell:{
    name:"FreeCell",
    cardinfo:{
      viewmode:"up",  //default direction cards are placed
      cardcount:[13]   //hearts,clubs,diamonds,spades
    },
    generalinfo:{
      redeals:0,
      checks:"none",
      autoplace:true
    },
    board:[[
      {vardef:{
        criteria:"any|same|asc|any"
      }},
      {type:"rest"},
      {type:"rest"},
      {type:"rest"},
      {type:"rest"},
      {vardef:{
        criteria:"0|same|asc|any"
      }},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"},
      {type:"collection"}
    ],[
      {vardef:{
        criteria:"14|alternate|desc|any"
      }},
      {type:"heap",startsize:7},
      {type:"heap",startsize:7},
      {type:"heap",startsize:7},
      {type:"heap",startsize:7},
      {type:"heap",startsize:6},
      {type:"heap",startsize:6},
      {type:"heap",startsize:6},
      {type:"heap",startsize:6}
    ]]
  },
  golf:{
    name:"Golf",
    cardinfo:{
      viewmode:"up",  //default direction cards are placed
      cardcount:[13]   //hearts,clubs,diamonds,spades
    },
    generalinfo:{
      redeals:0,
      checks:"none",
      maxstack:1,
      autoplace:true
    },
    board:[[
      {vardef:{
        criteria:"0|same|asc|any|null|anysuit|true",
        addclass:"noplace"
      }},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5},
      {type:"heap",startsize:5},
    ],[
      {type:"deck",mode:"heap",dealcount:1},
      {type:"collection",criteria:"-1|any|any|any"}
    ]]
  }
};
